// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClassifyImage(arg1, arg2) {
  return window['go']['main']['App']['ClassifyImage'](arg1, arg2);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetImageList() {
  return window['go']['main']['App']['GetImageList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetCategory(arg1) {
  return window['go']['main']['App']['SetCategory'](arg1);
}

export function SetImgDir() {
  return window['go']['main']['App']['SetImgDir']();
}
