// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClassifyImage(arg1:string,arg2:string):Promise<void>;

export function GetCategories():Promise<Array<string>>;

export function GetImageList():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function SetCategory(arg1:string):Promise<void>;

export function SetImgDir():Promise<string>;
